//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemaCustomer
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CustomerCodeUnitRema", ConfigurationName="RemaCustomer.CustomerCodeUnitRema_Port")]
    public interface CustomerCodeUnitRema_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/CustomerCodeUnitRema:GetCustomerName", ReplyAction="*")]
        System.Threading.Tasks.Task<RemaCustomer.GetCustomerName_Result> GetCustomerNameAsync(RemaCustomer.GetCustomerName request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerName", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CustomerCodeUnitRema", IsWrapped=true)]
    public partial class GetCustomerName
    {
        
        public GetCustomerName()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerName_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CustomerCodeUnitRema", IsWrapped=true)]
    public partial class GetCustomerName_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CustomerCodeUnitRema", Order=0)]
        public string return_value;
        
        public GetCustomerName_Result()
        {
        }
        
        public GetCustomerName_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface CustomerCodeUnitRema_PortChannel : RemaCustomer.CustomerCodeUnitRema_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class CustomerCodeUnitRema_PortClient : System.ServiceModel.ClientBase<RemaCustomer.CustomerCodeUnitRema_Port>, RemaCustomer.CustomerCodeUnitRema_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CustomerCodeUnitRema_PortClient() : 
                base(CustomerCodeUnitRema_PortClient.GetDefaultBinding(), CustomerCodeUnitRema_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CustomerCodeUnitRema_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerCodeUnitRema_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(CustomerCodeUnitRema_PortClient.GetBindingForEndpoint(endpointConfiguration), CustomerCodeUnitRema_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerCodeUnitRema_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CustomerCodeUnitRema_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerCodeUnitRema_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CustomerCodeUnitRema_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerCodeUnitRema_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RemaCustomer.GetCustomerName_Result> RemaCustomer.CustomerCodeUnitRema_Port.GetCustomerNameAsync(RemaCustomer.GetCustomerName request)
        {
            return base.Channel.GetCustomerNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<RemaCustomer.GetCustomerName_Result> GetCustomerNameAsync()
        {
            RemaCustomer.GetCustomerName inValue = new RemaCustomer.GetCustomerName();
            return ((RemaCustomer.CustomerCodeUnitRema_Port)(this)).GetCustomerNameAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomerCodeUnitRema_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomerCodeUnitRema_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://mathias:7047/BC140/WS/CRONUS International Ltd./Codeunit/CustomerCodeUnitR" +
                        "ema");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CustomerCodeUnitRema_PortClient.GetBindingForEndpoint(EndpointConfiguration.CustomerCodeUnitRema_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CustomerCodeUnitRema_PortClient.GetEndpointAddress(EndpointConfiguration.CustomerCodeUnitRema_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            CustomerCodeUnitRema_Port,
        }
    }
}
